### ISSUE TITLE
options.allowedHosts[0] should be a non-empty string

### ISSUE THREAD

**Issue by jlulich** [hyperledger/firefly-ui#139]
Also receiving this error upon npm run start:
Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.allowedHosts[0] should be a non-empty string.

**Comment by eberger727** [comment]
Please leave more information on the steps you took so that this issue can be reproduced. Also, make sure you are running a FireFly stack when you start the UI. Instructions to create a FireFly stack can be found [here](https://hyperledger.github.io/firefly/gettingstarted/firefly_cli.html). 

The TL;DR is:
- `go install github.com/hyperledger/firefly-cli/ff@latest`
- `ff init <stack_name> 2`
- `ff start <stack_name>`

**Comment by eberger727** [comment]
Closing due to staleness and no information to reproduce
